apiVersion: batch/v1
kind: Job
metadata:
  name: api-migration
  namespace: tech-challenge-namespace
  labels:
    app.kubernetes.io/name: api-migration
    app.kubernetes.io/part-of: tech-challenge-pos-fiap
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-migration
        app.kubernetes.io/part-of: tech-challenge-pos-fiap
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: tech-challenge-api-migrations:latest
          imagePullPolicy: Always
          command:
            - yarn
            - migrate:up
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
